// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditFieldController from "./edit_field_controller"
application.register("edit-field", EditFieldController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import StatusSelectController from "./status_select_controller"
application.register("status-select", StatusSelectController)
