development:
  a_check_task_expirations:
    class: Tasks::CheckExpirationsJob
    queue: recurring
    schedule: every 12 hours
production:
  a_check_task_expirations:
    class: Tasks::CheckExpirationsJob
    queue: expirations
    schedule: at 1am every day